version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gfhdfjhtj67
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassw0rd
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassw0rd
      - DB_NAME=testdb

volumes:
  db_data:
