name: Release
on:
  push:
    branches:
      - master

env:
  ECR_REGISTRY: 155009719402.dkr.ecr.ca-central-1.amazonaws.com
  ECR_REPOSITORY: nbc-venm-app
  AWS_REGION: ca-central-1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g semantic-release@21.0.2 @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release -e @semantic-release/github
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Git Tag
        id: git_tag
        run: echo "::set-env name=GIT_TAG::$(git describe --abbrev=0 --tags)"

      - name: Build Docker Image
        run: docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.GIT_TAG }} .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.GIT_TAG }}

  deploy:
    name: Deploy to ECS
    needs: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to AWS ECS Fargate
        run: echo "Deployed to AWS ECS Fargate"